name: forecast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - pystan==2.19.1.1
      - click
      - fbprophet
      - prophet
      - pandas
      - mlflow
      - pyspark